/*  :ts=8 bk=0
 *
 * sound.h:	Symbolic definitions for sound effects.
 *
 * Leo L. Schwab					9308.04
 */

enum SoundFX {
	SFX_GUNZAP = 1,
	SFX_GUNDRAINED,
	SFX_GUNEMPTY,
	SFX_DOORLOCKED,
	SFX_OPENDOOR,
	SFX_CLOSEDOOR,
	SFX_FLOORTRIGGER,
	SFX_GRABKEY,
	SFX_GRABHEALTH,
	SFX_GRABAMMO,
	SFX_GRABMONEY,
	SFX_GRABLIFE,
	SFX_GRABTALISMAN,
	SFX_CANTGRAB,
	SFX_OUCHSMALL,
	SFX_OUCHMED,
	SFX_OUCHBIG,
	MAX_SFX
};
